version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - 3306:3306
  app:
    build:
      context: .
      dockerfile: ./docker/prj/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql                 